### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by thgh** [bothrs/eslint-config#9]
Some errors I consider not fixing:

- [ ]  @typescript-eslint/no-explicit-any
- [ ]  react/prop-types: 'navigation.navigate' is missing in props validation
- [ ]  @typescript-eslint/no-unused-vars: 'React' is defined but never used
- [ ]  sonarjs/no-duplicate-string: justifyContent: 'space-between'
- [ ]  @typescript-eslint/no-empty-function
- [ ] sonarjs/no-gratuitous-expressions `icon={icon || 'info'}`
- [ ] @typescript-eslint/ban-ts-comment

**Comment by FabianMeul** [comment]
**@typescript-eslint/no-explicit-any**
I agree with the statement in the rule description:
> Using the `any` type defeats the purpose of using TypeScript. When `any` is used, all compiler type checks around that value are ignored.

If a type is unknown, it should be typed as `unknown`.

**react/prop-types**
That's specific to your use case, but it looks like `navigation` is not properly typed?

**@typescript-eslint/no-unused-vars**
The ESLint package implies React17, where an import of React in tsx-files is no longer necessary. This could be an issue with one of our linters, so we should check that out.

**sonarjs/no-duplicate-string**
Agreed, but it makes me wonder... Can that specific styling not be refactored to be re-usable?

**@typescript-eslint/no-empty-function**
Why would you want empty functions in your codebase?

**sonarjs/no-gratuitous-expressions**
I think nullish coalescing is a better pattern for that specific use-case.
Need to check out why it errors on that line.

**@typescript-eslint/ban-ts-comment**
I think it's okay to allow TS-Comments if they have a valid reason; https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-ts-comment.md#allow-with-description

**Comment by bramdeba** [comment]
**@typescript-eslint/no-explicit-any**
I agree with Fabian on using `unknown` instead of `any`.

**@typescript-eslint/no-unused-vars**
Might indeed cause some trouble with older projects. Can be easily disabled for these projects, no? I think it's really nice to have it on new projects as a default.

**sonarjs/no-duplicate-string**
With styled components, this seems annoying and I don't think it's a good idea to start creating constants for css values that are used multiple times on a page. We could create some sort of whitelist, but seems like a daunting task.
 
**@typescript-eslint/no-empty-function**
I get why you wouldn't want the empty functions to be removed automatically. I save all the time and would find it frustrating if I just created an empty function for it to be removed when saving the file casually. Wouldn't mind ESLInt complaining about it though.

**sonarjs/no-gratuitous-expressions**
Using OR or nullish coalescing depends on what you want to achieve. I believe both should be allowed. 

**@typescript-eslint/ban-ts-comment**
Following Fabian here.

**Comment by thgh** [comment]
Didn't see the responses until now.

The intermediate solution to apply this config to existing projects is to explicitly disable some rules. During further development these rules can then be enabled.

I see the value in 

- @typescript-eslint/no-explicit-any
- @typescript-eslint/no-unused-vars (warn, not error)

I don't see value in

- sonarjs/no-gratuitous-expressions -> It's massively used and easy to understand.
- @typescript-eslint/ban-ts-comment -> If you know what you are doing, it's really annoying to have to ignore an extra warning. The whole reason I put a ts comment is to hide a warning, why show another one... 🤣 
- sonarjs/no-duplicate-string -> Linter does not have enough context to know why I duplicate something, it may be just me, but this warning throws me off because it makes think of strategies to write more compact styles which does benefit anyone.
- @typescript-eslint/no-empty-function -> The error came from a mandatory click handler: `onPress={() => {}}`, this rule is not fixable, it just compains.

For dogpal-app I'm using these customizations (73 problems remaining, down from 1000+)
```json
    "settings": {
      "react": {
        "version": "detect"
      }
    },
    "plugins": [
      "simple-import-sort"
    ],
    "rules": {
      "@typescript-eslint/ban-ts-comment": 0,
      "@typescript-eslint/no-explicit-any": 0,
      "@typescript-eslint/no-unused-vars": 0,
      "import/no-default-export": 0,
      "import/no-named-as-default": 0,
      "import/order": 0,
      "jest/no-unus-functions": 0,
      "unicorn/filename-case": 0,
      "unicorn/no-null": 0,
      "unicorn/prevent-abbreviations": 0,
      "unused-imports/no-unused-imports": 0,
      "unused-imports/no-unused-vars": "warn",
      "simple-import-sort/imports": [
        "warn"
      ]
    }
```
